Repository thebaldehit/jungleBlog, pull requests merged in 2023-11, with the labels that each got.

#3 Initial setup
  jungleBlog/.gitignore
  jungleBlog/README.md
  jungleBlog/index.html
  jungleBlog/jsconfig.json
  jungleBlog/package-lock.json
  jungleBlog/package.json
  jungleBlog/public/vite.svg
  jungleBlog/src/App.svelte
  jungleBlog/src/app.css
  jungleBlog/src/assets/svelte.svg
  jungleBlog/src/lib/Counter.svelte
  jungleBlog/src/main.js
  jungleBlog/src/vite-env.d.ts
  jungleBlog/svelte.config.js
  jungleBlog/vite.config.js
Labels: front

#6 Added basic components
  jungleBlog/index.html
  jungleBlog/src/App.svelte
  jungleBlog/src/app.css
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Footer.svelte
  jungleBlog/src/components/Header.svelte
Labels: enhancement, front

#9 Feature/content
  jungleBlog/src/App.svelte
  jungleBlog/src/assets/images/sixth.png
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front, design

#10 Added card component
  jungleBlog/src/app.css
  jungleBlog/src/articles.js
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front, design

#11 Added custom cursor and pointer
  jungleBlog/src/app.css
  jungleBlog/src/assets/images/cursor.png
  jungleBlog/src/assets/images/pointer.png
  jungleBlog/src/components/Header.svelte
Labels: enhancement, front, design

#12 Added custom scrollbar
  jungleBlog/src/app.css
  jungleBlog/src/components/Card.svelte
Labels: enhancement, front, design

#14 Added article component
  jungleBlog/src/app.css
  jungleBlog/src/components/Article.svelte
Labels: enhancement, front, design

#17 Feature/fixlayout
  jungleBlog/index.html
  jungleBlog/src/app.css
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Footer.svelte
  jungleBlog/src/components/Header.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front, design

#18 Added routing (closes #15)
  jungleBlog/public/res/fifth.png
  jungleBlog/public/res/first.png
  jungleBlog/public/res/fourth.png
  jungleBlog/public/res/pointer.png
  jungleBlog/public/res/second.png
  jungleBlog/public/res/sixth.png
  jungleBlog/public/res/third.png
  jungleBlog/public/vite.svg
  jungleBlog/src/App.svelte
  jungleBlog/src/app.css
  jungleBlog/src/articles.js
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Header.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front, design

#19 Init server side
  backend/.gitignore
  backend/config/config.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: enhancement, back

#20 FIxed bug and made small changes
  jungleBlog/public/res/cursor.png
  jungleBlog/src/app.css
  jungleBlog/src/articles.js
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Content.svelte
Labels: bug, enhancement, front

#22 Added dark theme on page
  jungleBlog/src/app.css
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Footer.svelte
  jungleBlog/src/components/Header.svelte
Labels: enhancement, front, design

#27 Impemented static server
  backend/fs/fs.js
  backend/mimetypes.js
  backend/server.js
Labels: back

#28 Added logger
  backend/fs/fs.js
  backend/logger/logger.js
  backend/server.js
Labels: enhancement, back

#29 Added optimization
  jungleBlog/index.html
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Footer.svelte
  jungleBlog/src/components/Header.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front, design

#32 Added burger menu
  jungleBlog/src/components/Header.svelte
Labels: enhancement, front, design

#35 Added init database script
  backend/config/config.js
  backend/db/create.js
  backend/db/db.sql
Labels: back

#40 Feature/strotyendpoint
  backend/controllers/static.js
  backend/controllers/story.js
  backend/server.js
Labels: back

#41 Fixed bug with routing
  jungleBlog/src/App.svelte
  jungleBlog/src/components/Article.svelte
Labels: bug, front
