Repository thebaldehit/jungleBlog, pull requests merged in 2023-12, with the labels that each got.

#45 Feature/commentendpoint
  backend/controllers/comment.js
  backend/server.js
Labels: back

#50 Added feedback component
  jungleBlog/src/App.svelte
  jungleBlog/src/components/Feedback.svelte
  jungleBlog/src/components/Header.svelte
Labels: enhancement, front, design

#53 Added theme saving in local storage
  jungleBlog/src/components/Header.svelte
  jungleBlog/src/main.js
Labels: bug, enhancement, front, design

#55 Added animations
  jungleBlog/src/components/AboutUs.svelte
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Feedback.svelte
Labels: enhancement, front, design

#57 Fixed bug in header navigation
  jungleBlog/src/App.svelte
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Header.svelte
Labels: bug, front

#58 Fixed bug when reload page on /article/:id
  backend/controllers/static.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: bug, back

#59 Fixed bug w pointer
  jungleBlog/src/components/Header.svelte
Labels: bug, front

#63 Made minor changes
  jungleBlog/src/components/Footer.svelte
  jungleBlog/src/components/Header.svelte
Labels: bug, enhancement

#64 Feature/returningexception
  backend/controllers/comment.js
  backend/controllers/story.js
Labels: enhancement, back

#65 Updated vite config
  jungleBlog/vite.config.js
Labels: enhancement

#67 Added GROUP BY to returning data
  backend/controllers/story.js
Labels: bug, back

#68 Added main image for dark theme
  jungleBlog/public/res/fifth.png
  jungleBlog/public/res/first.png
  jungleBlog/public/res/fourth.png
  jungleBlog/public/res/mainPhoto.png
  jungleBlog/public/res/second.png
  jungleBlog/public/res/third.png
  jungleBlog/src/components/Content.svelte
Labels: enhancement, front

#69 Added dark-theme photo
  jungleBlog/public/res/mainPhotoDark.png
Labels: enhancement, front

#71 Added themes for 30 days
  backend/data/thmesForStories.json
Labels: front, back

#72 Fixed layout shift
  jungleBlog/src/app.css
  jungleBlog/src/components/AboutUs.svelte
  jungleBlog/src/components/Header.svelte
Labels: bug, front, design

#74 Added bussines logic
  backend/.env.sample
  backend/config/config.js
  backend/contentGenerator.js
  backend/data/nextThemeIndex.json
  backend/data/thmesForStories.json
  backend/fs/fs.js
  backend/gpt-api/gptApi.js
  backend/gpt-api/toolsesForApi.js
  backend/logger/logger.js
  backend/package-lock.json
  backend/package.json
Labels: enhancement, back

#78 Change stories table
  backend/db/db.sql
Labels: enhancement, back
