Repository thebaldehit/jungleBlog, pull requests merged in 2024-01, with the labels that each got.

#80 Added logger and benchmark for content generator
  backend/contentGenerator.js
  backend/gpt-api/toolsesForApi.js
  backend/logger/logger.js
Labels: enhancement, back

#81 Changed logger invocation in server side
  backend/controllers/comment.js
  backend/controllers/static.js
  backend/controllers/story.js
  backend/logger/logger.js
  backend/server.js
Labels: enhancement, back

#82 Added entry point
  backend/contentGenerator.js
  backend/index.js
Labels: enhancement, back

#83 Added mimeTypes folder
  backend/controllers/comment.js
  backend/controllers/static.js
  backend/controllers/story.js
  backend/mimeTypes/mimetypes.js
Labels: enhancement, back

#84 Added fetching
  jungleBlog/src/articlesStore.js
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front, design

#88 Feature/caching
  backend/cacher/cacher.js
  backend/cacher/cacherSingleton.js
  backend/config/config.js
  backend/contentGenerator.js
  backend/controllers/comment.js
  backend/controllers/static.js
  backend/controllers/story.js
  backend/server.js
Labels: enhancement, back

#90 Added image url to story data
  backend/controllers/story.js
Labels: bug, enhancement, back

#91 Fixed bug w/ reloding
  jungleBlog/src/components/Article.svelte
Labels: bug, enhancement, front

#92 Fix bug when reloading about and feedback pages
  backend/controllers/static.js
Labels: bug, back

#94 Added cacher algoritms
  backend/cacher/cacher.js
  backend/cacher/cacherSingleton.js
  backend/config/config.js
Labels: enhancement, back

#95 Added image fetching
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
Labels: enhancement, front, design

#96 Added web sockets to server
  backend/contentGenerator.js
  backend/controllers/ws.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: enhancement, back

#98 Made small changes
  jungleBlog/src/articles.js
  jungleBlog/src/components/AboutUs.svelte
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Feedback.svelte
  jungleBlog/src/components/Main.svelte
Labels: enhancement, front

#99 Added functionality for comments
  jungleBlog/src/components/Article.svelte
Labels: enhancement, front, design

#100 Added websockets
  jungleBlog/src/articlesStore.js
  jungleBlog/src/components/Article.svelte
Labels: enhancement, front

#101 Featurelinter
  backend/.eslintrc.js
  backend/cacher/cacherSingleton.js
  backend/config/config.js
  backend/controllers/comment.js
  backend/controllers/static.js
  backend/controllers/story.js
  backend/db/create.js
  backend/fs/fs.js
  backend/gpt-api/gptApi.js
  backend/gpt-api/toolsesForApi.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: enhancement, back

#105 Added name saving to local storage
  jungleBlog/src/components/Article.svelte
Labels: enhancement, front

#106 Added feedback logic
  jungleBlog/src/components/Feedback.svelte
Labels: enhancement, front

#107 Added scripts for building and copy files to backend static folder
  jungleBlog/package.json
Labels: enhancement, front

#108 Added ability to define in url quantity of comments
  backend/controllers/comment.js
Labels: enhancement, back

#110 Deleted useless file
  jungleBlog/src/lib/Counter.svelte
Labels: enhancement

#113 Fixed url and made minor changes
  jungleBlog/.env
  jungleBlog/src/components/Article.svelte
Labels: enhancement, front

#114 Admin panel
  adminPanel/.env
  adminPanel/.gitignore
  adminPanel/README.md
  adminPanel/index.html
  adminPanel/jsconfig.json
  adminPanel/package-lock.json
  adminPanel/package.json
  adminPanel/src/App.svelte
  adminPanel/src/app.css
  adminPanel/src/assets/svelte.svg
  adminPanel/src/components/Comment.svelte
  adminPanel/src/components/Comments.svelte
  adminPanel/src/components/Feedback.svelte
  adminPanel/src/components/Feedbacks.svelte
  adminPanel/src/components/Navigation.svelte
  adminPanel/src/components/Stories.svelte
  adminPanel/src/components/Story.svelte
  adminPanel/src/main.js
  adminPanel/src/store.js
  adminPanel/src/utils.js
  adminPanel/src/vite-env.d.ts
  adminPanel/svelte.config.js
  adminPanel/vite.config.js
Labels: enhancement, front

#115 Added feedback table to DB
  backend/db/db.sql
Labels: enhancement, back

#117 Added feedback controller
  backend/controllers/feedback.js
Labels: enhancement, back

#118 Changes in controllers for admin panel
  backend/controllers/comment.js
  backend/controllers/story.js
  backend/server.js
Labels: enhancement, back

#120 Added websockets on main page
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Main.svelte
  jungleBlog/src/main.js
  jungleBlog/src/websocketStore.js
Labels: enhancement, front

#121 Delete unnecessary controller
  backend/controllers/comment.js
  backend/server.js
Labels: enhancement, back

#122 Fix bug in delete comment controller
  backend/controllers/comment.js
Labels: bug, back

#123 Feature/login
  adminPanel/src/App.svelte
  adminPanel/src/components/Login.svelte
  backend/.env.sample
  backend/config/config.js
  backend/controllers/comment.js
  backend/controllers/login.js
  backend/controllers/story.js
  backend/server.js
Labels: enhancement, front, back

#124 Changed static controller
  backend/controllers/static.js
Labels: enhancement, back

#125 Fix bug when reloading page on article page
  backend/controllers/static.js
Labels: bug, back

#130 Update Readme.md
  README.md
Labels: documentation

#131 Fixed bug w/ websockets
  jungleBlog/src/components/Article.svelte
Labels: bug, enhancement, front

#132 Delete unnecessary console.log
  adminPanel/src/App.svelte
Labels: enhancement, front

#135 Added feedback posting and websockets
  jungleBlog/src/components/Feedback.svelte
Labels: enhancement, front

#136 Refactored front via prettier
  jungleBlog/src/App.svelte
  jungleBlog/src/articlesStore.js
  jungleBlog/src/components/AboutUs.svelte
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Card.svelte
  jungleBlog/src/components/Content.svelte
  jungleBlog/src/components/Feedback.svelte
  jungleBlog/src/components/Header.svelte
  jungleBlog/src/components/Main.svelte
  jungleBlog/src/main.js
  jungleBlog/src/websocketStore.js
Labels: enhancement, front, design

#137 Added censoring for comments
  jungleBlog/src/bannedWords.js
  jungleBlog/src/components/Article.svelte
Labels: enhancement, front

#138 Implemented autoreloading feedbacks
  adminPanel/src/components/Navigation.svelte
  backend/controllers/ws.js
Labels: enhancement, front, back

#139 Fixed bug with images
  jungleBlog/src/components/Article.svelte
Labels: bug, enhancement, front

#140 Stop generating stories when all is done
  backend/.env.sample
  backend/config/config.js
  backend/contentGenerator.js
  backend/data/nextThemeIndex.json
Labels: bug, enhancement, back

#142 Fixed bug w/ comments visibility
  jungleBlog/src/components/Article.svelte
Labels: bug, enhancement, front

#141 Upgraded title
  jungleBlog/src/components/Card.svelte
Labels: enhancement, front, design

#144 Fixed acces to feedbacks
  backend/controllers/feedback.js
  backend/controllers/login.js
Labels: bug, enhancement, back

#146 Move updating cache from content generator to ws controller
  backend/contentGenerator.js
  backend/controllers/ws.js
Labels: enhancement, back

#148 Added fav ico
  jungleBlog/index.html
  jungleBlog/public/res/cowboyico.ico
Labels: enhancement, front, design

#147 Fixed bug w/ header and small changes in footer
  jungleBlog/src/components/Footer.svelte
  jungleBlog/src/components/Header.svelte
Labels: bug, enhancement, front, design

#149 Added new fav ico
  jungleBlog/index.html
  jungleBlog/public/res/cowboyico.ico
  jungleBlog/public/res/fav.ico
Labels: enhancement, front, design

#150 Fixed a mistake in function arguments
  backend/controllers/feedback.js
Labels: bug, back

#151 Added ability changes protocols
  adminPanel/.env.sample
  adminPanel/src/App.svelte
  adminPanel/src/components/Comment.svelte
  adminPanel/src/components/Navigation.svelte
  adminPanel/src/components/Story.svelte
  adminPanel/src/store.js
  backend/.env.sample
  backend/config/config.js
  backend/controllers/comment.js
  jungleBlog/.env.sample
  jungleBlog/src/components/Article.svelte
  jungleBlog/src/components/Feedback.svelte
  jungleBlog/src/websocketStore.js
Labels: enhancement, front, back

#152 Delted .env files
  adminPanel/.env
  adminPanel/.gitignore
  jungleBlog/.env
  jungleBlog/.gitignore
Labels: enhancement, front, back
